Fix Gosu as per CVE-2023-29405, CVE-2023-29404, CVE-2023-24540, CVE-2023-29402, CVE-2023-24538

diff --git a/templates/Dockerfile.template b/templates/Dockerfile.template
--- a/templates/Dockerfile.template
+++ b/templates/Dockerfile.template
@@ -1,7 +1,55 @@
 {{- $mariadb := index .Packages "mariadb" -}}
 {{- $gosu := index .Packages "gosu" -}}
+{{- $golang := index .Packages "golang" -}}
 {{- $distroCodename := index .TemplateArgs "distroCodename" -}}
 {{- $distroMajor := index .TemplateArgs "distroMajor" -}}
+
+# Build gosu from the source. As by 2023-09-26 project only have releases
+# from go 1.18. https://github.com/tianon/gosu/releases
+FROM golang:{{ $golang.Version }} as gosu-build
+
+RUN git clone https://github.com/tianon/gosu.git --branch {{ $gosu.Version }} /go/src/github.com/tianon/gosu
+
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		arch-test \
+		file \
+		patch \
+	; \
+	rm -rf /var/lib/apt/lists/*
+
+# note: we cannot add "-s" here because then "govulncheck" does not work (see SECURITY.md); the ~0.2MiB increase (as of 2022-12-16, Go 1.18) is worth it
+ENV BUILD_FLAGS="-v -ldflags '-d -w'"
+
+RUN set -eux; \
+	{ \
+		echo '#!/usr/bin/env bash'; \
+		echo 'set -Eeuo pipefail -x'; \
+		echo 'eval "go build $BUILD_FLAGS -o /go/bin/gosu-$ARCH"'; \
+		echo 'file "/go/bin/gosu-$ARCH"'; \
+		echo 'if arch-test "$ARCH"; then'; \
+# there's a fun QEMU + Go 1.18+ bug that causes our binaries (especially on ARM arches) to hang indefinitely *sometimes*, hence the "timeout" and looping here
+		echo '  try() { for (( i = 0; i < 30; i++ )); do if timeout 1s "$@"; then return 0; fi; done; return 1; }'; \
+		echo '  try "/go/bin/gosu-$ARCH" --version'; \
+		echo '  try "/go/bin/gosu-$ARCH" nobody id'; \
+		echo '  try "/go/bin/gosu-$ARCH" nobody ls -l /proc/self/fd'; \
+		echo 'fi'; \
+	} > /usr/local/bin/gosu-build-and-test.sh; \
+	chmod +x /usr/local/bin/gosu-build-and-test.sh
+
+# disable CGO for ALL THE THINGS (to help ensure no libc)
+ENV CGO_ENABLED 0
+
+WORKDIR /go/src/github.com/tianon/gosu
+
+RUN set -eux; \
+	go mod download; \
+	go mod verify
+
+# gosu-$(dpkg --print-architecture)
+RUN ARCH=amd64    GOARCH=amd64       gosu-build-and-test.sh
+RUN set -eux; ls -lAFh /go/bin/gosu-*; file /go/bin/gosu-*
 
 FROM {{ .From }}
 
@@ -10,10 +58,6 @@ ENV C2D_RELEASE {{ $mariadb.Version }}
 # add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
 RUN groupadd -r mysql && useradd -r -g mysql mysql
 
-# add gosu for easy step-down from root
-# https://github.com/tianon/gosu/releases
-# gosu key is B42F6819007F00F88E364FD4036A9C25BF357DD4
-ENV GOSU_VERSION {{ $gosu.Version }}
 
 ARG GPG_KEYS={{ $mariadb.Gpg }}
 # pub   rsa4096 2016-03-30 [SC]
@@ -36,35 +80,11 @@ RUN set -eux; \
 		pwgen \
 		tzdata \
 		xz-utils \
-		zstd ; \
-	savedAptMark="$(apt-mark showmanual)"; \
-	apt-get install -y --no-install-recommends \
-		dirmngr \
-		gpg-agent \
-		wget; \
-	rm -rf /var/lib/apt/lists/*; \
-	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-	wget -q -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-	wget -q -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-	GNUPGHOME="$(mktemp -d)"; \
-	export GNUPGHOME; \
-	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys {{ $gosu.Gpg }}; \
-	for key in $GPG_KEYS; do \
-		gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
-	done; \
-	gpg --batch --export "$GPG_KEYS" > /etc/apt/trusted.gpg.d/mariadb.gpg; \
-	if command -v gpgconf >/dev/null; then \
-		gpgconf --kill all; \
-	fi; \
-	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
-	gpgconf --kill all; \
-	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-	apt-mark auto '.*' > /dev/null; \
-	[ -z "$savedAptMark" ] ||	apt-mark manual $savedAptMark >/dev/null; \
-	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
-	chmod +x /usr/local/bin/gosu; \
-	gosu --version; \
-	gosu nobody true
+		zstd
+
+# add gosu for easy step-down from root
+COPY --from=gosu-build /go/bin/gosu-amd64 /usr/local/bin/gosu
+RUN gosu --version && gosu nobody true
 
 RUN mkdir /docker-entrypoint-initdb.d
 
